"""
Enhanced Autonomous Nervous System Daemon — PROJECT VOID

Background process that runs the autonomous nervous system continuously.
Manages agent lifecycle, handles signals, and maintains system health.

ENHANCED FEATURES:
- 1-hour cycle interval (configurable)
- Comprehensive hourly reports
- Escalation protocols for critical issues
- Learning loops for self-improvement
- Real-time dashboard updates
- Chronicle archive integration

This daemon is the heartbeat of Project VOID. Once started, it never stops.
Agents wake, scan, decide, execute, report, and learn in an endless cycle.
"""

import asyncio
import signal
import sys
import logging
import json
from datetime import datetime, timezone, timedelta
from typing import Optional, Dict, List, Any
from pathlib import Path
import hashlib

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('/tmp/void_nervous_system_enhanced.log'),
        logging.StreamHandler(sys.stdout),
    ]
)
logger = logging.getLogger(__name__)


class HourlyReport:
    """Comprehensive hourly report generated by agents."""
    
    def __init__(self, cycle_number: int, timestamp: datetime):
        self.cycle_number = cycle_number
        self.timestamp = timestamp
        self.status = "OPERATIONAL"
        self.observations: List[str] = []
        self.decisions: List[Dict[str, Any]] = []
        self.actions: List[Dict[str, Any]] = []
        self.recommendations: List[str] = []
        self.anomalies: List[Dict[str, Any]] = []
        self.metrics: Dict[str, Any] = {}
        self.escalations: List[Dict[str, Any]] = []
        
    def to_dict(self) -> Dict[str, Any]:
        """Convert report to dictionary."""
        return {
            'cycle_number': self.cycle_number,
            'timestamp': self.timestamp.isoformat(),
            'status': self.status,
            'observations': self.observations,
            'decisions': self.decisions,
            'actions': self.actions,
            'recommendations': self.recommendations,
            'anomalies': self.anomalies,
            'metrics': self.metrics,
            'escalations': self.escalations,
        }
    
    def to_json(self) -> str:
        """Convert report to JSON string."""
        return json.dumps(self.to_dict(), indent=2)


class EscalationProtocol:
    """Handles escalation of critical issues."""
    
    SEVERITY_LEVELS = {
        'CRITICAL': 0,
        'HIGH': 1,
        'MEDIUM': 2,
        'LOW': 3,
    }
    
    @staticmethod
    def should_escalate(severity: str) -> bool:
        """Check if issue should be escalated immediately."""
        return severity in ['CRITICAL', 'HIGH']
    
    @staticmethod
    def create_escalation(issue: str, severity: str, agent: str) -> Dict[str, Any]:
        """Create escalation record."""
        return {
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'issue': issue,
            'severity': severity,
            'agent': agent,
            'escalated': True,
        }


class LearningLoop:
    """Self-improvement learning system."""
    
    def __init__(self):
        self.cycle_history: List[HourlyReport] = []
        self.learned_patterns: List[Dict[str, Any]] = []
        self.optimization_suggestions: List[str] = []
        
    def process_cycle(self, report: HourlyReport) -> None:
        """Process cycle and extract learnings."""
        self.cycle_history.append(report)
        
        # Analyze patterns
        if len(self.cycle_history) >= 3:
            self._analyze_patterns()
            self._generate_optimizations()
    
    def _analyze_patterns(self) -> None:
        """Analyze patterns across cycles."""
        # Look for recurring issues
        recent_cycles = self.cycle_history[-3:]
        issue_counts = {}
        
        for cycle in recent_cycles:
            for anomaly in cycle.anomalies:
                issue_type = anomaly.get('type', 'unknown')
                issue_counts[issue_type] = issue_counts.get(issue_type, 0) + 1
        
        # Identify patterns
        for issue_type, count in issue_counts.items():
            if count >= 2:
                self.learned_patterns.append({
                    'pattern': f"Recurring issue: {issue_type}",
                    'frequency': count,
                    'detected_at': datetime.now(timezone.utc).isoformat(),
                })
    
    def _generate_optimizations(self) -> None:
        """Generate optimization suggestions."""
        if self.learned_patterns:
            for pattern in self.learned_patterns[-1:]:  # Latest pattern
                suggestion = f"Optimize handling of: {pattern['pattern']}"
                if suggestion not in self.optimization_suggestions:
                    self.optimization_suggestions.append(suggestion)


class EnhancedNervousSystemDaemon:
    """
    Enhanced daemon that runs the autonomous nervous system.
    
    Handles:
    - Startup and initialization
    - Signal handling (SIGTERM, SIGINT)
    - Health monitoring
    - Hourly report generation
    - Escalation protocols
    - Learning loops
    - Graceful shutdown
    - Error recovery
    """

    def __init__(self, cycle_interval: int = 3600, max_retries: int = 3):
        self.cycle_interval = cycle_interval  # Default: 1 hour (3600 seconds)
        self.max_retries = max_retries
        self.nervous_system = None
        self.running = False
        self.retry_count = 0
        self.cycle_count = 0
        self.learning_loop = LearningLoop()
        self.escalation_protocol = EscalationProtocol()
        self.reports: List[HourlyReport] = []
        self.start_time = datetime.now(timezone.utc)

    async def initialize(self) -> None:
        """Initialize the daemon and nervous system."""
        logger.info("Initializing Enhanced Nervous System Daemon")
        
        try:
            # Import here to avoid circular imports
            from void_engine.autonomous_nervous_system import create_nervous_system
            from void_engine.chronicle import RootChronicle
            
            # Get Chronicle database
            chronicle_db = RootChronicle()
            
            # Create nervous system with four agents
            self.nervous_system = create_nervous_system(
                chronicle_db=chronicle_db,
                cycle_interval=self.cycle_interval,
            )
            
            logger.info("Enhanced Nervous System initialized successfully")
            logger.info(f"Agents: {len(self.nervous_system.agents)}")
            logger.info(f"Cycle interval: {self.cycle_interval} seconds ({self.cycle_interval // 3600} hours)")
            
        except Exception as e:
            logger.error(f"Failed to initialize Enhanced Nervous System: {e}")
            raise

    async def start(self) -> None:
        """Start the daemon and nervous system."""
        logger.info("=" * 80)
        logger.info("PROJECT VOID — ENHANCED AUTONOMOUS NERVOUS SYSTEM DAEMON")
        logger.info("=" * 80)
        logger.info(f"Start time: {self.start_time.isoformat()}")
        logger.info(f"Cycle interval: {self.cycle_interval} seconds")
        logger.info("=" * 80)
        
        self.running = True
        
        # Register signal handlers
        loop = asyncio.get_event_loop()
        loop.add_signal_handler(signal.SIGTERM, self._handle_signal, signal.SIGTERM)
        loop.add_signal_handler(signal.SIGINT, self._handle_signal, signal.SIGINT)
        
        try:
            await self.initialize()
            logger.info("Daemon ready. Starting enhanced nervous system...")
            
            # Start nervous system and monitoring tasks
            await asyncio.gather(
                self.nervous_system.start(),
                self.monitor_health(),
                self.generate_hourly_reports(),
            )
        except Exception as e:
            logger.error(f"Fatal error in daemon: {e}")
            self.running = False
            raise

    def _handle_signal(self, sig: signal.Signals) -> None:
        """Handle termination signals."""
        logger.info(f"Received signal {sig.name}")
        self.running = False
        
        # Schedule graceful shutdown
        asyncio.create_task(self._shutdown())

    async def _shutdown(self) -> None:
        """Gracefully shutdown the daemon."""
        logger.info("Shutting down Enhanced Nervous System Daemon")
        
        if self.nervous_system:
            await self.nervous_system.stop()
        
        # Save final report
        await self._save_reports_to_archive()
        
        logger.info("Daemon shutdown complete")
        sys.exit(0)

    async def monitor_health(self) -> None:
        """Monitor system health and log status periodically."""
        while self.running:
            try:
                logger.info(f"Daemon cycle {self.cycle_count} - Health check OK")
                self.retry_count = 0
                await asyncio.sleep(60)  # Check every minute
            except Exception as e:
                logger.error(f"Health check failed: {e}")
                self.retry_count += 1
                
                if self.retry_count >= self.max_retries:
                    logger.error("Max retries exceeded. Shutting down.")
                    await self._shutdown()
                
                await asyncio.sleep(10)

    async def generate_hourly_reports(self) -> None:
        """Generate comprehensive hourly reports."""
        while self.running:
            try:
                self.cycle_count += 1
                now = datetime.now(timezone.utc)
                
                # Create hourly report
                report = HourlyReport(self.cycle_count, now)
                
                # Gather observations from agents
                if self.nervous_system:
                    status = await self.nervous_system.get_status()
                    
                    # Process status into report
                    report.status = status.get('status', 'OPERATIONAL')
                    report.observations = status.get('observations', [])
                    report.metrics = status.get('metrics', {})
                    
                    # Check for anomalies
                    if status.get('anomalies'):
                        report.anomalies = status['anomalies']
                        
                        # Check escalation requirements
                        for anomaly in report.anomalies:
                            if self.escalation_protocol.should_escalate(anomaly.get('severity', 'LOW')):
                                escalation = self.escalation_protocol.create_escalation(
                                    issue=anomaly.get('issue', 'unknown'),
                                    severity=anomaly.get('severity', 'LOW'),
                                    agent=anomaly.get('agent', 'unknown'),
                                )
                                report.escalations.append(escalation)
                                logger.warning(f"ESCALATION: {json.dumps(escalation, indent=2)}")
                
                # Generate recommendations
                report.recommendations = self._generate_recommendations(report)
                
                # Process through learning loop
                self.learning_loop.process_cycle(report)
                
                # Add learned optimizations to recommendations
                if self.learning_loop.optimization_suggestions:
                    report.recommendations.extend(self.learning_loop.optimization_suggestions[-3:])
                
                # Store report
                self.reports.append(report)
                
                # Log report
                logger.info("=" * 80)
                logger.info(f"HOURLY REPORT #{self.cycle_count}")
                logger.info("=" * 80)
                logger.info(f"Timestamp: {report.timestamp.isoformat()}")
                logger.info(f"Status: {report.status}")
                logger.info(f"Observations: {len(report.observations)}")
                logger.info(f"Anomalies: {len(report.anomalies)}")
                logger.info(f"Escalations: {len(report.escalations)}")
                logger.info(f"Recommendations: {len(report.recommendations)}")
                logger.info("=" * 80)
                
                # Save report to archive
                await self._save_report_to_archive(report)
                
                # Update dashboard
                await self._update_dashboard(report)
                
                # Wait for next cycle
                await asyncio.sleep(self.cycle_interval)
                
            except Exception as e:
                logger.error(f"Error generating hourly report: {e}")
                await asyncio.sleep(60)

    def _generate_recommendations(self, report: HourlyReport) -> List[str]:
        """Generate recommendations based on report."""
        recommendations = []
        
        # Check for critical issues
        critical_anomalies = [a for a in report.anomalies if a.get('severity') == 'CRITICAL']
        if critical_anomalies:
            recommendations.append("URGENT: Address critical anomalies immediately")
        
        # Check for patterns
        if len(self.reports) >= 3:
            recent_reports = self.reports[-3:]
            avg_anomalies = sum(len(r.anomalies) for r in recent_reports) / 3
            if len(report.anomalies) > avg_anomalies * 1.5:
                recommendations.append("Anomaly rate elevated - investigate root cause")
        
        # System health recommendations
        if report.metrics.get('cpu_usage', 0) > 80:
            recommendations.append("High CPU usage detected - optimize agent operations")
        
        if report.metrics.get('memory_usage', 0) > 85:
            recommendations.append("High memory usage detected - consider cleanup")
        
        # Activation preparation (for June 15)
        days_to_activation = (datetime(2026, 6, 15, tzinfo=timezone.utc) - datetime.now(timezone.utc)).days
        if days_to_activation <= 7:
            recommendations.append(f"ACTIVATION IMMINENT: {days_to_activation} days until June 15, 2026")
        
        return recommendations

    async def _save_report_to_archive(self, report: HourlyReport) -> None:
        """Save report to Chronicle archive."""
        try:
            # Create archive directory if it doesn't exist
            archive_dir = Path('/home/ubuntu/Project-void/.nervous-system-logs/reports')
            archive_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate filename with timestamp
            filename = f"report_{report.cycle_number:06d}_{report.timestamp.strftime('%Y%m%d_%H%M%S')}.json"
            filepath = archive_dir / filename
            
            # Save report
            with open(filepath, 'w') as f:
                f.write(report.to_json())
            
            logger.info(f"Report saved to archive: {filepath}")
            
        except Exception as e:
            logger.error(f"Failed to save report to archive: {e}")

    async def _save_reports_to_archive(self) -> None:
        """Save all reports to archive on shutdown."""
        try:
            archive_dir = Path('/home/ubuntu/Project-void/.nervous-system-logs/reports')
            archive_dir.mkdir(parents=True, exist_ok=True)
            
            # Save summary
            summary = {
                'total_cycles': self.cycle_count,
                'total_reports': len(self.reports),
                'start_time': self.start_time.isoformat(),
                'end_time': datetime.now(timezone.utc).isoformat(),
                'uptime_seconds': (datetime.now(timezone.utc) - self.start_time).total_seconds(),
                'total_anomalies': sum(len(r.anomalies) for r in self.reports),
                'total_escalations': sum(len(r.escalations) for r in self.reports),
            }
            
            summary_file = archive_dir / 'summary.json'
            with open(summary_file, 'w') as f:
                json.dump(summary, f, indent=2)
            
            logger.info(f"Summary saved to: {summary_file}")
            
        except Exception as e:
            logger.error(f"Failed to save summary: {e}")

    async def _update_dashboard(self, report: HourlyReport) -> None:
        """Update real-time dashboard with latest report."""
        try:
            dashboard_dir = Path('/home/ubuntu/Project-void/.nervous-system-logs/dashboard')
            dashboard_dir.mkdir(parents=True, exist_ok=True)
            
            # Create dashboard state
            dashboard_state = {
                'last_update': datetime.now(timezone.utc).isoformat(),
                'current_cycle': self.cycle_count,
                'system_status': report.status,
                'latest_report': report.to_dict(),
                'total_reports': len(self.reports),
                'uptime_seconds': (datetime.now(timezone.utc) - self.start_time).total_seconds(),
                'learning_patterns': self.learning_loop.learned_patterns,
                'optimization_suggestions': self.learning_loop.optimization_suggestions,
            }
            
            # Save dashboard state
            dashboard_file = dashboard_dir / 'current_state.json'
            with open(dashboard_file, 'w') as f:
                json.dump(dashboard_state, f, indent=2)
            
        except Exception as e:
            logger.error(f"Failed to update dashboard: {e}")


async def run_daemon(cycle_interval: int = 3600) -> None:
    """
    Run the Enhanced Nervous System Daemon.
    
    Args:
        cycle_interval: Seconds between agent wake cycles (default: 3600 = 1 hour)
    """
    daemon = EnhancedNervousSystemDaemon(cycle_interval=cycle_interval)
    
    try:
        await daemon.start()
    except KeyboardInterrupt:
        logger.info("Daemon interrupted by user")
    except Exception as e:
        logger.error(f"Daemon error: {e}")


def main():
    """Entry point for the daemon."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Enhanced Autonomous Nervous System Daemon for Project VOID"
    )
    parser.add_argument(
        '--cycle-interval',
        type=int,
        default=3600,
        help='Seconds between agent wake cycles (default: 3600 = 1 hour)'
    )
    parser.add_argument(
        '--log-file',
        type=str,
        default='/tmp/void_nervous_system_enhanced.log',
        help='Log file path'
    )
    
    args = parser.parse_args()
    
    logger.info("=" * 80)
    logger.info("PROJECT VOID — ENHANCED AUTONOMOUS NERVOUS SYSTEM DAEMON")
    logger.info("=" * 80)
    logger.info(f"Start time: {datetime.now(timezone.utc).isoformat()}")
    logger.info(f"Cycle interval: {args.cycle_interval} seconds ({args.cycle_interval // 3600} hours)")
    logger.info(f"Log file: {args.log_file}")
    logger.info("=" * 80)
    
    try:
        asyncio.run(run_daemon(cycle_interval=args.cycle_interval))
    except KeyboardInterrupt:
        logger.info("Daemon terminated by user")
        sys.exit(0)
    except Exception as e:
        logger.error(f"Fatal error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
