from __future__ import annotations

import json
import sqlite3
from typing import Any, Dict, List, Optional

from void_engine.db_pool import get_db


def _is_sqlite(conn) -> bool:
    return isinstance(getattr(conn, "_real_conn", conn), sqlite3.Connection)


def _ph(conn) -> str:
    return "?" if _is_sqlite(conn) else "%s"


def _sql_value(value):
    if isinstance(value, (list, tuple, dict)):
        return json.dumps(value, ensure_ascii=False)
    return value


def _id_column_sql(conn) -> str:
    if _is_sqlite(conn):
        return "INTEGER PRIMARY KEY"
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def init_knowledge_tree_tables() -> None:
    conn = get_db()
    try:
        cur = conn.cursor()
        id_column = _id_column_sql(conn)
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS knowledge_tree_nodes (
                id {id_column},
                source TEXT NOT NULL,
                source_title TEXT NOT NULL,
                text_chars INTEGER DEFAULT 0,
                preview TEXT,
                overall_score REAL,
                head_score REAL,
                heart_score REAL,
                gut_score REAL,
                name_index INTEGER,
                name TEXT,
                meaning TEXT,
                frequency_hz REAL,
                chladni_mode TEXT,
                codon_hex TEXT,
                codon_glyph TEXT,
                adriana_signal TEXT,
                raw_payload TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(source, source_title)
            )
            """
        )
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS knowledge_tree_import_runs (
                id {id_column},
                source_path TEXT NOT NULL,
                format TEXT NOT NULL,
                processed_count INTEGER DEFAULT 0,
                skipped_count INTEGER DEFAULT 0,
                last_title TEXT,
                checkpoint_payload TEXT,
                status TEXT DEFAULT 'running',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(source_path, format)
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


def upsert_knowledge_tree_node(record: Dict[str, Any]) -> None:
    conn = get_db()
    try:
        ph = _ph(conn)
        cur = conn.cursor()
        values = [
            record["source"],
            record["title"],
            record.get("text_chars", 0),
            record.get("preview", ""),
            record["tree"].get("overall"),
            record["tree"].get("head"),
            record["tree"].get("heart"),
            record["tree"].get("gut"),
            record["tree"].get("name_index"),
            record["tree"].get("name"),
            record["tree"].get("meaning"),
            record["tree"].get("frequency_hz"),
            record["tree"].get("chladni_mode"),
            record["tree"].get("codon", {}).get("codon_hex"),
            record["tree"].get("codon", {}).get("glyph"),
            record["tree"].get("adriana_signal"),
            json.dumps(record, ensure_ascii=False),
        ]
        values = [_sql_value(value) for value in values]
        placeholders = ", ".join([ph] * len(values))
        updated_at_expr = "CURRENT_TIMESTAMP"
        query = f"""
            INSERT INTO knowledge_tree_nodes (
                source, source_title, text_chars, preview,
                overall_score, head_score, heart_score, gut_score,
                name_index, name, meaning, frequency_hz, chladni_mode,
                codon_hex, codon_glyph, adriana_signal, raw_payload
            ) VALUES ({placeholders})
            ON CONFLICT(source, source_title) DO UPDATE SET
                text_chars = excluded.text_chars,
                preview = excluded.preview,
                overall_score = excluded.overall_score,
                head_score = excluded.head_score,
                heart_score = excluded.heart_score,
                gut_score = excluded.gut_score,
                name_index = excluded.name_index,
                name = excluded.name,
                meaning = excluded.meaning,
                frequency_hz = excluded.frequency_hz,
                chladni_mode = excluded.chladni_mode,
                codon_hex = excluded.codon_hex,
                codon_glyph = excluded.codon_glyph,
                adriana_signal = excluded.adriana_signal,
                raw_payload = excluded.raw_payload,
                updated_at = {updated_at_expr}
        """
        cur.execute(query, values)
        conn.commit()
    finally:
        conn.close()


def upsert_import_run(
    source_path: str,
    format_name: str,
    processed_count: int,
    skipped_count: int,
    last_title: str,
    checkpoint_payload: Dict[str, Any],
    status: str,
) -> None:
    conn = get_db()
    try:
        ph = _ph(conn)
        cur = conn.cursor()
        values = [
            source_path,
            format_name,
            processed_count,
            skipped_count,
            last_title,
            json.dumps(checkpoint_payload, ensure_ascii=False),
            status,
        ]
        placeholders = ", ".join([ph] * len(values))
        query = f"""
            INSERT INTO knowledge_tree_import_runs (
                source_path, format, processed_count, skipped_count,
                last_title, checkpoint_payload, status
            ) VALUES ({placeholders})
            ON CONFLICT(source_path, format) DO UPDATE SET
                processed_count = excluded.processed_count,
                skipped_count = excluded.skipped_count,
                last_title = excluded.last_title,
                checkpoint_payload = excluded.checkpoint_payload,
                status = excluded.status,
                updated_at = CURRENT_TIMESTAMP
        """
        cur.execute(query, values)
        conn.commit()
    finally:
        conn.close()


def get_import_run(source_path: str, format_name: str) -> Optional[Dict[str, Any]]:
    conn = get_db()
    try:
        ph = _ph(conn)
        cur = conn.cursor()
        cur.execute(
            f"SELECT source_path, format, processed_count, skipped_count, last_title, checkpoint_payload, status, updated_at FROM knowledge_tree_import_runs WHERE source_path = {ph} AND format = {ph}",
            (source_path, format_name),
        )
        row = cur.fetchone()
        if not row:
            return None
        payload = row[5]
        if isinstance(payload, str):
            try:
                payload = json.loads(payload)
            except Exception:
                payload = {}
        return {
            "source_path": row[0],
            "format": row[1],
            "processed_count": row[2],
            "skipped_count": row[3],
            "last_title": row[4],
            "checkpoint_payload": payload or {},
            "status": row[6],
            "updated_at": row[7],
        }
    finally:
        conn.close()


def search_knowledge_tree_nodes(query: str = "", limit: int = 50, offset: int = 0) -> List[Dict[str, Any]]:
    conn = get_db()
    try:
        ph = _ph(conn)
        cur = conn.cursor()
        if query:
            like = f"%{query}%"
            cur.execute(
                f"""
                SELECT source, source_title, preview, overall_score, name, meaning, frequency_hz, codon_glyph, codon_hex, updated_at
                FROM knowledge_tree_nodes
                WHERE LOWER(source_title) LIKE LOWER({ph}) OR LOWER(preview) LIKE LOWER({ph}) OR LOWER(name) LIKE LOWER({ph}) OR LOWER(meaning) LIKE LOWER({ph})
                ORDER BY overall_score DESC, updated_at DESC
                LIMIT {ph} OFFSET {ph}
                """,
                (like, like, like, like, limit, offset),
            )
        else:
            cur.execute(
                f"""
                SELECT source, source_title, preview, overall_score, name, meaning, frequency_hz, codon_glyph, codon_hex, updated_at
                FROM knowledge_tree_nodes
                ORDER BY updated_at DESC, overall_score DESC
                LIMIT {ph} OFFSET {ph}
                """,
                (limit, offset),
            )
        rows = cur.fetchall()
        return [
            {
                "source": row[0],
                "title": row[1],
                "preview": row[2],
                "overall": row[3],
                "name": row[4],
                "meaning": row[5],
                "frequency_hz": row[6],
                "glyph": row[7],
                "codon_hex": row[8],
                "updated_at": str(row[9]),
            }
            for row in rows
        ]
    finally:
        conn.close()


def get_knowledge_tree_node(source: str, title: str) -> Optional[Dict[str, Any]]:
    conn = get_db()
    try:
        ph = _ph(conn)
        cur = conn.cursor()
        cur.execute(
            f"SELECT raw_payload, updated_at FROM knowledge_tree_nodes WHERE source = {ph} AND source_title = {ph}",
            (source, title),
        )
        row = cur.fetchone()
        if not row:
            return None
        payload = row[0]
        if isinstance(payload, str):
            payload = json.loads(payload)
        payload["updated_at"] = str(row[1])
        return payload
    finally:
        conn.close()


def get_knowledge_tree_stats() -> Dict[str, Any]:
    conn = get_db()
    try:
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) FROM knowledge_tree_nodes")
        total = cur.fetchone()[0]
        cur.execute("SELECT AVG(overall_score), AVG(frequency_hz) FROM knowledge_tree_nodes")
        row = cur.fetchone()
        cur.execute("SELECT source, COUNT(*) AS c FROM knowledge_tree_nodes GROUP BY source ORDER BY c DESC LIMIT 10")
        sources = [{"source": r[0], "count": r[1]} for r in cur.fetchall()]
        return {
            "total_nodes": total,
            "avg_overall": round(float(row[0]), 2) if row and row[0] is not None else 0.0,
            "avg_frequency_hz": round(float(row[1]), 2) if row and row[1] is not None else 0.0,
            "top_sources": sources,
        }
    finally:
        conn.close()
