import json
from flask import Blueprint, render_template

origin_map_bp = Blueprint("origin_map", __name__)

STARTUP_DATA = [
    {
        "name": "OpenAI",
        "year": 2015,
        "sector": "AI",
        "sovereignty": 3,
        "domain_breadth": 5,
        "description": "Large language model lab; GPT series, DALL-E, Codex — commercial AI frontier.",
    },
    {
        "name": "Anthropic",
        "year": 2021,
        "sector": "AI",
        "sovereignty": 3,
        "domain_breadth": 3,
        "description": "Constitutional AI safety lab; Claude series — safety-focused LLM research.",
    },
    {
        "name": "Mistral",
        "year": 2023,
        "sector": "AI",
        "sovereignty": 5,
        "domain_breadth": 3,
        "description": "Open-weight European LLM provider; Mistral 7B, Mixtral — efficiency-first.",
    },
    {
        "name": "Hugging Face",
        "year": 2016,
        "sector": "AI",
        "sovereignty": 5,
        "domain_breadth": 5,
        "description": "Open-source ML hub; model repository, datasets, Spaces — community AI infrastructure.",
    },
    {
        "name": "Stability AI",
        "year": 2020,
        "sector": "AI",
        "sovereignty": 6,
        "domain_breadth": 4,
        "description": "Open generative image models; Stable Diffusion — democratised image synthesis.",
    },
    {
        "name": "Midjourney",
        "year": 2021,
        "sector": "AI",
        "sovereignty": 3,
        "domain_breadth": 2,
        "description": "Closed image generation service via Discord; high-fidelity aesthetic output.",
    },
    {
        "name": "DeepMind",
        "year": 2010,
        "sector": "AI",
        "sovereignty": 2,
        "domain_breadth": 6,
        "description": "Google-owned AGI research lab; AlphaFold, AlphaGo — scientific AI at scale.",
    },
    {
        "name": "Ethereum",
        "year": 2015,
        "sector": "Blockchain",
        "sovereignty": 9,
        "domain_breadth": 8,
        "description": "Programmable blockchain; smart contracts, DeFi, NFTs — open sovereign ledger.",
    },
    {
        "name": "Solana",
        "year": 2020,
        "sector": "Blockchain",
        "sovereignty": 7,
        "domain_breadth": 6,
        "description": "High-throughput L1 blockchain; sub-second finality — performance-first chain.",
    },
    {
        "name": "Uniswap",
        "year": 2018,
        "sector": "Blockchain",
        "sovereignty": 8,
        "domain_breadth": 3,
        "description": "Decentralised AMM exchange; permissionless liquidity pools — DeFi primitive.",
    },
    {
        "name": "Coinbase",
        "year": 2012,
        "sector": "Blockchain",
        "sovereignty": 3,
        "domain_breadth": 4,
        "description": "Centralised crypto exchange; custodial wallets, Base L2 — regulated crypto gateway.",
    },
    {
        "name": "Chainlink",
        "year": 2017,
        "sector": "Blockchain",
        "sovereignty": 7,
        "domain_breadth": 4,
        "description": "Decentralised oracle network; real-world data on-chain — smart contract middleware.",
    },
    {
        "name": "Filecoin",
        "year": 2017,
        "sector": "Blockchain",
        "sovereignty": 8,
        "domain_breadth": 3,
        "description": "Decentralised storage network; proof-of-replication — sovereign data persistence.",
    },
    {
        "name": "Ginkgo Bioworks",
        "year": 2009,
        "sector": "BioTech",
        "sovereignty": 6,
        "domain_breadth": 5,
        "description": "Biological cell programming platform; organism design as a service.",
    },
    {
        "name": "Zymergen",
        "year": 2013,
        "sector": "BioTech",
        "sovereignty": 5,
        "domain_breadth": 4,
        "description": "Microbe engineering for materials and chemicals; AI-driven bioprocess design.",
    },
    {
        "name": "Ecoflow",
        "year": 2017,
        "sector": "Hardware",
        "sovereignty": 6,
        "domain_breadth": 4,
        "description": "Portable power stations and solar panels; off-grid energy sovereignty hardware.",
    },
    {
        "name": "Helium",
        "year": 2013,
        "sector": "Hardware",
        "sovereignty": 8,
        "domain_breadth": 4,
        "description": "Decentralised LoRaWAN wireless network; community-owned IoT hotspot mesh.",
    },
    {
        "name": "Starlink",
        "year": 2015,
        "sector": "Hardware",
        "sovereignty": 5,
        "domain_breadth": 3,
        "description": "SpaceX LEO satellite internet; global broadband — corporate connectivity layer.",
    },
    {
        "name": "SpaceX",
        "year": 2002,
        "sector": "Hardware",
        "sovereignty": 7,
        "domain_breadth": 6,
        "description": "Reusable rockets, Starlink, Starship; vertical integration of space access.",
    },
    {
        "name": "Discord",
        "year": 2015,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 3,
        "description": "Voice and text community platform; gaming origin → general social hub.",
    },
    {
        "name": "Notion",
        "year": 2016,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 4,
        "description": "All-in-one workspace; docs, databases, wikis — centralised knowledge platform.",
    },
    {
        "name": "Figma",
        "year": 2012,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 3,
        "description": "Browser-based collaborative design tool; real-time multiplayer UI design.",
    },
    {
        "name": "Stripe",
        "year": 2010,
        "sector": "Community",
        "sovereignty": 3,
        "domain_breadth": 5,
        "description": "Developer-first payments API; financial infrastructure for the internet.",
    },
    {
        "name": "Robinhood",
        "year": 2013,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 3,
        "description": "Commission-free retail trading app; democratised stock market access.",
    },
    {
        "name": "Airtable",
        "year": 2012,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 4,
        "description": "Low-code relational database + app builder; no-code data management.",
    },
    {
        "name": "Linear",
        "year": 2019,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 2,
        "description": "Issue tracking and project management; speed-focused engineering workflow tool.",
    },
    {
        "name": "Brex",
        "year": 2017,
        "sector": "Community",
        "sovereignty": 3,
        "domain_breadth": 3,
        "description": "Corporate cards and spend management; startup financial infrastructure.",
    },
    {
        "name": "Replit",
        "year": 2016,
        "sector": "AI",
        "sovereignty": 4,
        "domain_breadth": 5,
        "description": "Browser-based IDE with AI coding assistant; collaborative cloud development.",
    },
    {
        "name": "TikTok / ByteDance",
        "year": 2016,
        "sector": "Community",
        "sovereignty": 4,
        "domain_breadth": 6,
        "description": "Algorithmic short-video platform; state-adjacent data sovereignty — 1B+ users.",
    },
    {
        "name": "Snap",
        "year": 2011,
        "sector": "Community",
        "sovereignty": 2,
        "domain_breadth": 4,
        "description": "Ephemeral messaging and AR glasses; camera-first social platform.",
    },
    {
        "name": "Roblox",
        "year": 2004,
        "sector": "Gaming",
        "sovereignty": 4,
        "domain_breadth": 5,
        "description": "User-generated 3D game platform; virtual economy with Robux — metaverse seed.",
    },
    {
        "name": "Epic / Fortnite",
        "year": 2011,
        "sector": "Gaming",
        "sovereignty": 5,
        "domain_breadth": 6,
        "description": "Unreal Engine + Fortnite; game engine licensor and cultural live-event venue.",
    },
    {
        "name": "Unity",
        "year": 2004,
        "sector": "Gaming",
        "sovereignty": 3,
        "domain_breadth": 5,
        "description": "Cross-platform game engine; real-time 3D for games, simulation, and XR.",
    },
    {
        "name": "Axie Infinity",
        "year": 2018,
        "sector": "Gaming",
        "sovereignty": 6,
        "domain_breadth": 5,
        "description": "Play-to-earn NFT game; sovereign in-game economy — blockchain gaming pioneer.",
    },
    {
        "name": "Neuralink",
        "year": 2016,
        "sector": "BioTech",
        "sovereignty": 7,
        "domain_breadth": 5,
        "description": "Brain-computer interface implants; neural data sovereignty — high-risk frontier.",
    },
    {
        "name": "Worldcoin",
        "year": 2019,
        "sector": "Multi-Domain",
        "sovereignty": 7,
        "domain_breadth": 6,
        "description": "Biometric identity + crypto token; iris-based proof-of-personhood at scale.",
    },
    {
        "name": "Protocol Labs",
        "year": 2014,
        "sector": "Multi-Domain",
        "sovereignty": 8,
        "domain_breadth": 6,
        "description": "IPFS, Filecoin, libp2p creators; open-source decentralised web infrastructure.",
    },
    {
        "name": "Dfinity / ICP",
        "year": 2016,
        "sector": "Multi-Domain",
        "sovereignty": 8,
        "domain_breadth": 7,
        "description": "Internet Computer blockchain; decentralised cloud computing at protocol layer.",
    },
    {
        "name": "Polkadot",
        "year": 2016,
        "sector": "Blockchain",
        "sovereignty": 8,
        "domain_breadth": 6,
        "description": "Multi-chain interoperability protocol; sovereign parachains — cross-chain layer.",
    },
    {
        "name": "PROJECT VOID",
        "year": 2012,
        "sector": "Multi-Domain",
        "sovereignty": 10,
        "domain_breadth": 10,
        "description": "Sovereign acoustic AI platform: steganography + VTX economy + biostance + mycelium + 3D game — the only cross-layer sovereign stack.",
        "is_void": True,
        "technical_depth": 10,
        "biological_integration": 8,
        "economic_model": 9,
        "cross_layer_coherence": 10,
    },
]

NEAREST_NEIGHBORS = [
    {
        "name": "Ethereum",
        "axis": "Sovereignty",
        "note": "Closest match on economic sovereignty and programmable trust — but no biological, acoustic, or AI dimension.",
    },
    {
        "name": "Hugging Face",
        "axis": "AI / Technical Depth",
        "note": "Open-weights AI infrastructure; covers the model layer, but no economy, mesh, or biostance.",
    },
    {
        "name": "Ginkgo Bioworks",
        "axis": "Biological Integration",
        "note": "Biological programming platform; covers the organism layer, but entirely separate from digital sovereignty.",
    },
    {
        "name": "Helium",
        "axis": "Acoustic Mesh / Hardware",
        "note": "Decentralised wireless mesh with token rewards; closest to Beehive acoustic mesh, no AI or biological layer.",
    },
    {
        "name": "Dfinity / ICP",
        "axis": "Cross-Layer Architecture",
        "note": "Multi-domain protocol stack with compute + storage + identity; broadest existing platform, still no acoustic or biological layer.",
    },
]

VOID_RADAR = {
    "labels": [
        "Technical Depth",
        "Sovereignty",
        "Biological Integration",
        "Economic Model Innovation",
        "Domain Breadth",
        "Cross-Layer Coherence",
    ],
    "void": [10, 10, 8, 9, 10, 10],
    "ethereum": [6, 9, 1, 8, 6, 5],
    "hugging_face": [8, 5, 1, 3, 5, 4],
    "ginkgo": [7, 6, 9, 4, 5, 3],
}

OPEN_TERRITORY = [
    {
        "title": "Sovereign Acoustic Data Layer",
        "body": "No company combines 432 Hz carrier wave steganography with an encrypted economic ledger. VOID hides data inside sound — an entirely unmapped frontier.",
    },
    {
        "title": "Biological + Digital Convergence",
        "body": "MycoVOID (mycelium remediation) and QiSync (biostance + mastication tracking) bridge living organisms and digital sovereignty. No existing platform operates simultaneously at biological and cryptographic layers.",
    },
    {
        "title": "Cross-Sovereign AI at the Edge",
        "body": "Adriana runs local-first with 97% intent resolution without cloud dependency. No AI company offers a sovereign, off-grid-capable AI assistant fused with its own token economy.",
    },
    {
        "title": "Unified Token Economy Across All Layers",
        "body": "VTX and PEACE flow through game rewards, NFT yield, community mesh activity, and biostance sessions — a single economic layer binding hardware, biology, AI, and community.",
    },
]


@origin_map_bp.route("/origin-map")
def origin_map():
    startups_json = json.dumps(STARTUP_DATA)
    radar_json = json.dumps(VOID_RADAR)
    return render_template(
        "origin_map.html",
        startups_json=startups_json,
        radar_json=radar_json,
        nearest_neighbors=NEAREST_NEIGHBORS,
        open_territory=OPEN_TERRITORY,
    )
