#!/usr/bin/env python3
"""
Vocal Resonance Pipeline
=======================

Reconstructs the missing "33-song" style analysis workflow in a reproducible way.

Capabilities:
1) Analyze vocal stems and compute:
   - dominantHz
   - energy432 / energy440
   - tuning labels
   - bridge score and carrier quality score
2) Classify tracks into sovereign / mixed_bridge / convention / error
3) Recommend top carriers for a target profile

Supports WAV directly. For MP3/M4A/other formats, this script uses ffmpeg to
decode into mono WAV for analysis.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import tempfile
import wave
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


SUPPORTED_EXTS = {".wav", ".mp3", ".m4a", ".flac", ".ogg", ".aac"}


@dataclass
class TrackAnalysis:
    index: int
    filename: str
    title: str
    duration_s: float
    sampleRate: int
    dominantHz: float
    energy432: float
    energy440: float
    tuning: str
    rms: float
    centroidHz: float
    resonance_margin: float
    bridge_score: float
    quality_score: float


def _format_duration(duration_s: float) -> str:
    total = max(0, int(round(duration_s)))
    mins = total // 60
    secs = total % 60
    return f"{mins}:{secs:02d}"


def export_typescript_music_library(
    tracks: list[TrackAnalysis],
    out_ts: Path,
    cdn_base_url: str = "",
) -> None:
    """
    Export analysis as Adriana-style TypeScript MUSIC_LIBRARY rows.

    Unknown fields (e.g., bitrate) are set to sensible placeholders.
    """
    out_ts.parent.mkdir(parents=True, exist_ok=True)

    rows: list[str] = []
    base = cdn_base_url.strip().rstrip("/")

    for t in tracks:
        if base:
            cdn_url = f"{base}/{t.filename}"
        else:
            cdn_url = ""

        row = {
            "index": t.index,
            "filename": t.filename,
            "title": t.title,
            "duration": _format_duration(t.duration_s),
            "duration_s": round(t.duration_s, 1),
            "sampleRate": t.sampleRate,
            "bitrate": 0,
            "dominantHz": t.dominantHz,
            "energy432": t.energy432,
            "energy440": t.energy440,
            "tuning": t.tuning,
            "rms": t.rms,
            "centroidHz": t.centroidHz,
            "cdnUrl": cdn_url,
        }
        rows.append("  " + json.dumps(row, ensure_ascii=False) + ",")

    content = (
        "// Auto-generated by scripts/vocal_resonance_pipeline.py\n"
        "// The Album. Sovereign vs Convention. The frequency microscope.\n"
        "export interface MusicTrack {\n"
        "  index: number;\n"
        "  filename: string;\n"
        "  title: string;\n"
        "  duration: string;\n"
        "  duration_s: number;\n"
        "  sampleRate: number;\n"
        "  bitrate: number;\n"
        "  dominantHz: number;\n"
        "  energy432: number;\n"
        "  energy440: number;\n"
        "  tuning: string;\n"
        "  rms: number;\n"
        "  centroidHz: number;\n"
        "  cdnUrl: string;\n"
        "}\n\n"
        "export const MUSIC_LIBRARY: MusicTrack[] = [\n"
        + "\n".join(rows)
        + "\n];\n"
    )

    out_ts.write_text(content, encoding="utf-8")


def separate_stems_ffmpeg(
    songs_dir: Path,
    vocals_dir: Path,
    accompaniment_dir: Path,
    overwrite: bool = False,
) -> tuple[int, int]:
    """
    Approximate vocal/instrument separation using center extraction.

    This is not as strong as a neural separator (e.g., Demucs), but it is
    dependency-light and reproducible for all users with ffmpeg installed.
    """
    vocals_dir.mkdir(parents=True, exist_ok=True)
    accompaniment_dir.mkdir(parents=True, exist_ok=True)

    processed = 0
    failed = 0

    for song in iter_audio_files(songs_dir):
        vocal_out = vocals_dir / f"{song.stem}_vocals.wav"
        acc_out = accompaniment_dir / f"{song.stem}_accompaniment.wav"

        if not overwrite and vocal_out.exists() and acc_out.exists():
            processed += 1
            continue

        cmd = [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-y" if overwrite else "-n",
            "-i",
            str(song),
            "-filter_complex",
            # Mid (L+R)/2 ~ vocal center; Side (L-R)/2 ~ accompaniment emphasis
            "[0:a]aformat=channel_layouts=stereo,pan=mono|c0=0.5*c0+0.5*c1[voc];"
            "[0:a]aformat=channel_layouts=stereo,pan=mono|c0=0.5*c0-0.5*c1[acc]",
            "-map",
            "[voc]",
            "-ar",
            "48000",
            "-ac",
            "1",
            str(vocal_out),
            "-map",
            "[acc]",
            "-ar",
            "48000",
            "-ac",
            "1",
            str(acc_out),
        ]

        try:
            subprocess.run(cmd, check=True)
            processed += 1
        except Exception:
            failed += 1

    return processed, failed


def _decode_to_mono_wav(src: Path) -> tuple[np.ndarray, int, float]:
    """Load an audio file as mono float32 [-1, 1], sample rate, duration seconds."""
    if src.suffix.lower() == ".wav":
        return _read_wav(src)

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_wav = Path(tmp.name)

    try:
        cmd = [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(src),
            "-ac",
            "1",
            "-ar",
            "48000",
            str(tmp_wav),
        ]
        subprocess.run(cmd, check=True)
        return _read_wav(tmp_wav)
    finally:
        try:
            tmp_wav.unlink(missing_ok=True)
        except OSError:
            pass


def _read_wav(path: Path) -> tuple[np.ndarray, int, float]:
    with wave.open(str(path), "rb") as wf:
        channels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        sr = wf.getframerate()
        frames = wf.getnframes()
        raw = wf.readframes(frames)

    if sampwidth == 1:
        data = np.frombuffer(raw, dtype=np.uint8).astype(np.float32)
        data = (data - 128.0) / 128.0
    elif sampwidth == 2:
        data = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    elif sampwidth == 4:
        data = np.frombuffer(raw, dtype=np.int32).astype(np.float32) / 2147483648.0
    else:
        raise ValueError(f"Unsupported WAV sample width: {sampwidth}")

    if channels > 1:
        data = data.reshape(-1, channels).mean(axis=1)

    duration = len(data) / float(sr) if sr > 0 else 0.0
    return data, sr, duration


def _spectral_features(samples: np.ndarray, sample_rate: int) -> tuple[float, float, float]:
    """Return (dominant_hz, rms, centroid_hz)."""
    if samples.size == 0 or sample_rate <= 0:
        return 0.0, 0.0, 0.0

    x = samples.astype(np.float32)
    rms = float(np.sqrt(np.mean(x * x)))

    # 16k sample window is enough for stable dominant tone estimate.
    n = min(len(x), 16384)
    if n < 1024:
        return 0.0, rms, 0.0

    windowed = x[:n] * np.hanning(n)
    spec = np.fft.rfft(windowed)
    mag = np.abs(spec)
    freqs = np.fft.rfftfreq(n, d=1.0 / sample_rate)

    mag[0] = 0.0
    peak_idx = int(np.argmax(mag)) if mag.size else 0
    dominant_hz = float(freqs[peak_idx]) if peak_idx < len(freqs) else 0.0

    mag_sum = float(np.sum(mag))
    centroid_hz = float(np.sum(freqs * mag) / mag_sum) if mag_sum > 1e-12 else 0.0
    return dominant_hz, rms, centroid_hz


def _band_energy(samples: np.ndarray, sample_rate: int, center_hz: float, half_width_hz: float = 2.0) -> float:
    if samples.size == 0 or sample_rate <= 0:
        return 0.0

    n = min(len(samples), 65536)
    if n < 2048:
        return 0.0

    x = samples[:n] * np.hanning(n)
    spec = np.fft.rfft(x)
    power = np.abs(spec) ** 2
    freqs = np.fft.rfftfreq(n, d=1.0 / sample_rate)

    low = center_hz - half_width_hz
    high = center_hz + half_width_hz
    band = (freqs >= low) & (freqs <= high)

    band_energy = float(np.sum(power[band]))
    total = float(np.sum(power)) + 1e-12
    return band_energy / total


def _normalize_pair(a: float, b: float) -> tuple[float, float]:
    s = a + b
    if s <= 1e-12:
        return 0.0, 0.0
    return a / s, b / s


def _classify_tuning(energy432: float, energy440: float, dominant_hz: float) -> str:
    if dominant_hz <= 0 or (energy432 == 0 and energy440 == 0):
        return "error"

    margin = energy432 - energy440
    if abs(margin) <= 0.06:
        return "Mixed / Atonal"
    if margin > 0:
        return "432 Hz (Sovereign)"
    return "440 Hz (Convention)"


def _bridge_score(energy432: float, energy440: float) -> float:
    """1.0 means perfectly centered between 432 and 440 energies."""
    return max(0.0, 1.0 - abs(energy432 - energy440))


def _quality_score(duration_s: float, rms: float, centroid_hz: float) -> float:
    """Heuristic score to avoid weak stems for document carriers."""
    dur_score = min(duration_s / 180.0, 1.0)  # full score at ~3 min
    rms_score = 1.0 - min(abs(rms - 0.18) / 0.18, 1.0)
    # Prefer avoiding extremely dull (<300) or extremely harsh (>6k) centroids
    if centroid_hz <= 0:
        cent_score = 0.0
    elif centroid_hz < 300:
        cent_score = 0.25
    elif centroid_hz <= 4500:
        cent_score = 1.0
    elif centroid_hz <= 6000:
        cent_score = 0.7
    else:
        cent_score = 0.4
    return max(0.0, min((0.4 * dur_score + 0.35 * rms_score + 0.25 * cent_score), 1.0))


def analyze_track(path: Path, index: int) -> TrackAnalysis:
    samples, sr, duration_s = _decode_to_mono_wav(path)
    dominant_hz, rms, centroid_hz = _spectral_features(samples, sr)

    raw_432 = _band_energy(samples, sr, 432.0)
    raw_440 = _band_energy(samples, sr, 440.0)
    energy432, energy440 = _normalize_pair(raw_432, raw_440)

    tuning = _classify_tuning(energy432, energy440, dominant_hz)
    margin = energy432 - energy440

    return TrackAnalysis(
        index=index,
        filename=path.name,
        title=path.stem,
        duration_s=round(duration_s, 1),
        sampleRate=sr,
        dominantHz=round(dominant_hz, 2),
        energy432=round(energy432, 3),
        energy440=round(energy440, 3),
        tuning=tuning,
        rms=round(rms, 4),
        centroidHz=round(centroid_hz, 1),
        resonance_margin=round(margin, 3),
        bridge_score=round(_bridge_score(energy432, energy440), 3),
        quality_score=round(_quality_score(duration_s, rms, centroid_hz), 3),
    )


def iter_audio_files(input_dir: Path) -> Iterable[Path]:
    for p in sorted(input_dir.iterdir()):
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS:
            yield p


def run_analyze(input_dir: Path, out_json: Path | None, out_csv: Path | None) -> list[TrackAnalysis]:
    tracks: list[TrackAnalysis] = []
    files = list(iter_audio_files(input_dir))
    for idx, file_path in enumerate(files):
        try:
            tracks.append(analyze_track(file_path, idx))
        except Exception:
            tracks.append(
                TrackAnalysis(
                    index=idx,
                    filename=file_path.name,
                    title=file_path.stem,
                    duration_s=0.0,
                    sampleRate=0,
                    dominantHz=0.0,
                    energy432=0.0,
                    energy440=0.0,
                    tuning="error",
                    rms=0.0,
                    centroidHz=0.0,
                    resonance_margin=0.0,
                    bridge_score=0.0,
                    quality_score=0.0,
                )
            )

    if out_json:
        payload = {
            "count": len(tracks),
            "tracks": [asdict(t) for t in tracks],
        }
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    if out_csv:
        out_csv.parent.mkdir(parents=True, exist_ok=True)
        with out_csv.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(asdict(tracks[0]).keys()) if tracks else [])
            if tracks:
                writer.writeheader()
                for t in tracks:
                    writer.writerow(asdict(t))

    return tracks


def load_tracks(path: Path) -> list[TrackAnalysis]:
    data = json.loads(path.read_text(encoding="utf-8"))
    raw = data.get("tracks", [])
    return [TrackAnalysis(**item) for item in raw]


def classify_groups(tracks: list[TrackAnalysis]) -> dict[str, list[TrackAnalysis]]:
    groups = {
        "sovereign": [],
        "mixed_bridge": [],
        "convention": [],
        "error": [],
    }
    for t in tracks:
        if t.tuning.startswith("432"):
            groups["sovereign"].append(t)
        elif t.tuning.startswith("440"):
            groups["convention"].append(t)
        elif t.tuning.lower().startswith("mixed"):
            groups["mixed_bridge"].append(t)
        else:
            groups["error"].append(t)
    return groups


def recommend_tracks(tracks: list[TrackAnalysis], target: str, top_n: int) -> list[TrackAnalysis]:
    scored: list[tuple[float, TrackAnalysis]] = []
    for t in tracks:
        if t.tuning == "error":
            continue

        if target == "sovereign":
            target_fit = max(0.0, t.resonance_margin)
        elif target == "convention":
            target_fit = max(0.0, -t.resonance_margin)
        else:  # bridge
            target_fit = t.bridge_score

        # Favor stems that are both target-fit and technically stable.
        score = 0.65 * target_fit + 0.35 * t.quality_score
        scored.append((score, t))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [t for _, t in scored[:top_n]]


def print_classification(tracks: list[TrackAnalysis]) -> None:
    groups = classify_groups(tracks)
    print("Classification Summary")
    print("----------------------")
    print(f"Total tracks: {len(tracks)}")
    print(f"Sovereign:   {len(groups['sovereign'])}")
    print(f"Mixed/Bridge:{len(groups['mixed_bridge'])}")
    print(f"Convention:  {len(groups['convention'])}")
    print(f"Error:       {len(groups['error'])}")


def print_recommendations(tracks: list[TrackAnalysis], target: str, top_n: int) -> None:
    picks = recommend_tracks(tracks, target=target, top_n=top_n)
    print(f"Top {len(picks)} recommendations for target='{target}'")
    print("------------------------------------------------")
    for i, t in enumerate(picks, start=1):
        print(
            f"{i:02d}. {t.title} | tuning={t.tuning} | "
            f"E432={t.energy432:.3f} E440={t.energy440:.3f} | "
            f"margin={t.resonance_margin:+.3f} | bridge={t.bridge_score:.3f} | quality={t.quality_score:.3f}"
        )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Analyze, classify, and recommend vocal carriers.")
    p.add_argument(
        "--songs-dir",
        type=Path,
        help="Directory with full songs. Use with --separate-first to produce vocal stems.",
    )
    p.add_argument(
        "--separate-first",
        action="store_true",
        help="Run FFmpeg vocal/accompaniment separation before analysis.",
    )
    p.add_argument(
        "--vocals-dir",
        type=Path,
        default=Path("data/vocal_stems/vocals"),
        help="Output directory for separated vocal stems.",
    )
    p.add_argument(
        "--accompaniment-dir",
        type=Path,
        default=Path("data/vocal_stems/accompaniment"),
        help="Output directory for separated accompaniment stems.",
    )
    p.add_argument(
        "--overwrite-stems",
        action="store_true",
        help="Overwrite existing separated stem files.",
    )
    p.add_argument("--input-dir", type=Path, help="Directory with vocal stems (wav/mp3/m4a/flac/ogg/aac).")
    p.add_argument("--analysis-json", type=Path, default=Path("data/vocal_resonance_analysis.json"))
    p.add_argument("--analysis-csv", type=Path, default=Path("data/vocal_resonance_analysis.csv"))
    p.add_argument(
        "--export-ts",
        type=Path,
        help="Optional path to export Adriana-style TypeScript MUSIC_LIBRARY.",
    )
    p.add_argument(
        "--cdn-base-url",
        default="",
        help="Optional CDN base URL used for cdnUrl when --export-ts is enabled.",
    )
    p.add_argument("--from-json", type=Path, help="Skip analysis and load an existing JSON analysis file.")
    p.add_argument("--target", choices=["sovereign", "bridge", "convention"], default="bridge")
    p.add_argument("--top-n", type=int, default=10)
    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.separate_first:
        if not args.songs_dir:
            parser.error("--songs-dir is required when --separate-first is used.")
        processed, failed = separate_stems_ffmpeg(
            songs_dir=args.songs_dir,
            vocals_dir=args.vocals_dir,
            accompaniment_dir=args.accompaniment_dir,
            overwrite=args.overwrite_stems,
        )
        print(f"Stem separation complete: processed={processed}, failed={failed}")

        # If no explicit analysis input was provided, analyze the generated vocals.
        if not args.input_dir:
            args.input_dir = args.vocals_dir

    if args.from_json:
        tracks = load_tracks(args.from_json)
    else:
        if not args.input_dir:
            parser.error("--input-dir is required unless --from-json is used.")
        tracks = run_analyze(args.input_dir, args.analysis_json, args.analysis_csv)
        print(f"Saved analysis JSON: {args.analysis_json}")
        print(f"Saved analysis CSV:  {args.analysis_csv}")

    print_classification(tracks)
    print()
    print_recommendations(tracks, target=args.target, top_n=args.top_n)

    if args.export_ts:
        export_typescript_music_library(tracks, args.export_ts, cdn_base_url=args.cdn_base_url)
        print()
        print(f"Exported TypeScript library: {args.export_ts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
